/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedBusinessesIndexRouteImport } from './routes/_authenticated/businesses.index'
import { Route as AuthenticatedBusinessesBusinessIdRouteImport } from './routes/_authenticated/businesses.$businessId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessesIndexRoute =
  AuthenticatedBusinessesIndexRouteImport.update({
    id: '/businesses/',
    path: '/businesses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessesBusinessIdRoute =
  AuthenticatedBusinessesBusinessIdRouteImport.update({
    id: '/businesses/$businessId',
    path: '/businesses/$businessId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/home': typeof AuthenticatedHomeRoute
  '/map': typeof AuthenticatedMapRoute
  '/businesses/$businessId': typeof AuthenticatedBusinessesBusinessIdRoute
  '/businesses/': typeof AuthenticatedBusinessesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/home': typeof AuthenticatedHomeRoute
  '/map': typeof AuthenticatedMapRoute
  '/businesses/$businessId': typeof AuthenticatedBusinessesBusinessIdRoute
  '/businesses': typeof AuthenticatedBusinessesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/businesses/$businessId': typeof AuthenticatedBusinessesBusinessIdRoute
  '/_authenticated/businesses/': typeof AuthenticatedBusinessesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/home'
    | '/map'
    | '/businesses/$businessId'
    | '/businesses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/home'
    | '/map'
    | '/businesses/$businessId'
    | '/businesses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/home'
    | '/_authenticated/map'
    | '/_authenticated/businesses/$businessId'
    | '/_authenticated/businesses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/businesses/': {
      id: '/_authenticated/businesses/'
      path: '/businesses'
      fullPath: '/businesses/'
      preLoaderRoute: typeof AuthenticatedBusinessesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/businesses/$businessId': {
      id: '/_authenticated/businesses/$businessId'
      path: '/businesses/$businessId'
      fullPath: '/businesses/$businessId'
      preLoaderRoute: typeof AuthenticatedBusinessesBusinessIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedBusinessesBusinessIdRoute: typeof AuthenticatedBusinessesBusinessIdRoute
  AuthenticatedBusinessesIndexRoute: typeof AuthenticatedBusinessesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedBusinessesBusinessIdRoute:
    AuthenticatedBusinessesBusinessIdRoute,
  AuthenticatedBusinessesIndexRoute: AuthenticatedBusinessesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
